[2023-03-28T05:56:23.885+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-03-12T00:00:00+00:00 map_index=2 [queued]>
[2023-03-28T05:56:24.452+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-03-12T00:00:00+00:00 map_index=2 [queued]>
[2023-03-28T05:56:24.453+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T05:56:24.453+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T05:56:24.453+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T05:56:24.971+0000] {taskinstance.py:1303} INFO - Executing <Mapped(_PythonDecoratedOperator): add_one> on 2022-03-12 00:00:00+00:00
[2023-03-28T05:56:24.997+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'example_dynamic_task_mapping', 'add_one', 'scheduled__2022-03-12T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', '/home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_dynamic_task_mapping.py', '--cfg-path', '/tmp/tmpeckkuyhp', '--map-index', '2']
[2023-03-28T05:56:24.999+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask add_one
[2023-03-28T05:56:25.046+0000] {standard_task_runner.py:55} INFO - Started process 129 to run task
[2023-03-28T05:57:17.606+0000] {task_command.py:388} INFO - Running <TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-03-12T00:00:00+00:00 map_index=2 [running]> on host 9119afc303d7
[2023-03-28T05:57:20.304+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task add_one ((MySQLdb.OperationalError) (1040, 'Too many connections')
(Background on this error at: https://sqlalche.me/e/14/e3q8); 129)
[2023-03-28T05:57:20.671+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T05:57:21.162+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
